[package]
name = "meshbool"
version = "0.0.0"
edition = "2024"

[features]

[dependencies]
nalgebra = { version = "0.34", default-features = false, features = ["std"] }

[dev-dependencies]
manifold-rs = { path = "./manifold-rs" }
approx = "0.5"
