# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = [
#   "-Clink-arg=-fuse-ld=lld",
#   "-Zshare-generics=yes",
#   "-Clink-arg=--ld-path=/usr/local/bin/mold", # you need mold installed.
# ]

[build]
# rustc-wrapper = "/home/midget/.cargo/bin/sccache"
rustflags = ["-C", "target-cpu=native", "-Z", "share-generics=yes"]
